server:
  port: 7777

accounts:
  datasource:
    url: jdbc:mysql://localhost:3306/account?serverTimezone=Europe/Warsaw&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_LOGIN}
    password: ${MYSQL_PASSWORD}
    ddl-mode: update

allow-get-accounts: false
